; PlatformIO Project Configuration File
;
; Sniffer WiFi pasivo + DNS forwarder + TinyML
; Board: ESP-WROOM-32 basico
; ============================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^6.21.3

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DCONFIG_LWIP_IP_FORWARD=1
    -DCONFIG_LWIP_IPV4_NAPT=1
    -DCONFIG_LWIP_L2_TO_L3_COPY=1
